import React, {useState, useRef, useEffect} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {IconPlus, IconRobot, IconSend, IconCopy, IconCheck, IconChevronDown, IconFileText, IconArrowUpRight, IconLoader2} from '@tabler/icons-react';

const sample = {
 question:'Git merge 和 rebase 有什么区别？',
 queries:['Git merge 如何合并分支？','Git rebase 如何整理提交历史？'],
 answer:'## 两种方式，都能整合分支\n\n### Merge：保留分支历史\nMerge 会整合两个分支的历史。当分支发生分叉时，通常会创建一个新的合并提交，保留分支的分叉与合并过程。适合需要保留完整开发历史、多人协作的场景。[资料1]\n\n### Rebase：形成线性历史\nRebase 会将当前分支的提交依次重新应用到目标分支之上，使提交历史更加线性。它会改写提交历史，通常用于整理尚未共享的本地提交。[资料2]\n\n### 主要区别对比\n\n| 对比项 | Merge | Rebase |\n| --- | --- | --- |\n| 提交历史 | 保留分叉与合并过程 | 形成线性提交历史 |\n| 历史可读性 | 展示分支协作过程 | 历史更简洁 |\n| 适用场景 | 共享分支、多人协作 | 整理本地未共享提交 |\n\n### 示例：使用 rebase 整理提交\n\n```bash\ngit switch feature\ngit rebase main\n```',
 sources:[{reference:'资料1',file_name:'progit.pdf',pages:[65,66],chunk_id:'progit_128',content:'当两个分支的历史发生分叉时，Git 可以通过三方合并整合它们，并创建一个合并提交。\n\n合并提交连接两个分支的历史，让你能够查看分支的分叉与合并过程。\n\n如果修改发生冲突，需要手动解决冲突后完成合并。'},{reference:'资料2',file_name:'progit.pdf',pages:[72],chunk_id:'progit_142',content:'变基会把当前分支上的提交，依次重新应用到目标分支上，从而形成线性的提交历史。\n\n这种方式可以让历史更易于阅读。不过，变基会改写提交，不应随意对其他人已经依赖的共享提交执行变基。'}], demo:true
};
function Copy({text}){const [done,setDone]=useState(false);return <button className="copy" aria-label="复制内容" onClick={async()=>{try{await navigator.clipboard.writeText(text);setDone(true);setTimeout(()=>setDone(false),1500)}catch{setDone(false)}}}>{done?<IconCheck size={15}/>:<IconCopy size={15}/>} {done?'已复制':'复制'}</button>}
function Markdown({text,onCitation}){return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>href?.startsWith('#source-')?<button className="citation" onClick={()=>onCitation(href.slice(8))}>{children}</button>:<a href={href} target="_blank" rel="noreferrer">{children}</a>,pre:({children})=><div className="code-wrap"><pre>{children}</pre></div>}}>{text.replace(/\[资料(\d+)\](?!\()/g,'[资料$1](#source-$1)')}</ReactMarkdown>}
export function App(){
 const [turns,setTurns]=useState([sample]),[selected,setSelected]=useState(0),[draft,setDraft]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[json,setJson]=useState({});const bottom=useRef(null), abort=useRef(null);const current=turns[selected];
 useEffect(()=>()=>abort.current?.abort(),[]);
 function citation(index,n){setSelected(index);setTimeout(()=>{const el=document.getElementById(`source-${n}`);if(el){el.open=true;el.scrollIntoView({behavior:'smooth',block:'center'});el.focus()}},60)}
 async function send(e){e?.preventDefault();const question=draft.trim();if(!question||loading)return;setError('');setLoading(true);abort.current=new AbortController();const timer=setTimeout(()=>abort.current.abort(),180000);try{const response=await fetch('/api/v1/rag/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question}),signal:abort.current.signal});if(!response.ok)throw new Error(response.status===422?'请输入有效的问题。':`请求失败（${response.status}），请检查问答服务。`);const data=await response.json();if(typeof data.answer!=='string'||!Array.isArray(data.queries)||!Array.isArray(data.sources))throw new Error('接口返回格式不正确，需要 answer、queries 和 sources。');setTurns(prev=>{const next=[...prev.filter(t=>!t.demo),{...data,question}];setSelected(next.length-1);return next});setDraft('');setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),80)}catch(err){setError(err.name==='AbortError'?'请求已取消或超时，请稍后重试。':err.message||'无法连接问答服务。')}finally{clearTimeout(timer);setLoading(false)}}
 function reset(){if(loading)return;setTurns([]);setSelected(0);setError('');setDraft('')}
 return <div className="app"><main className="main"><header><div className="brand">知识库问答 <span>RAG / Pro Git</span></div><div style={{display:'flex',alignItems:'center',gap:14}}><a href="/" style={{color:'#088b8b',fontSize:13,fontWeight:600,textDecoration:'none'}}>人才搜索</a><button className="primary new" onClick={reset} disabled={loading}><IconPlus size={18}/>新对话</button></div></header><section className="conversation" aria-label="对话记录">
 {!turns.length&&<div className="empty"><IconRobot size={40}/><h1>从一个问题开始</h1><p>根据知识库回答，展开查看拆分问题与引用原文。</p><button onClick={()=>setDraft(sample.question)} className="suggestion">{sample.question}<IconArrowUpRight size={18}/></button><button className="text-button" onClick={()=>{setTurns([sample]);setSelected(0)}}>查看示例</button></div>}
 {turns.map((turn,i)=><article key={i} className="turn"><div className="user-row"><div className="avatar user">我</div><div className="question">{turn.question}</div></div><div className="turn-meta">{turn.demo?'示例数据 · 回答与页码仅用于展示':'知识库回答'}<button onClick={()=>setSelected(i)} className="text-button">{selected===i?'正在查看本轮资料':'查看本轮资料'}</button></div><div className="answer-row"><div className="avatar bot"><IconRobot size={21}/></div><div className={'answer '+(selected===i?'selected':'')}><div className="answer-toolbar"><span>根据参考资料生成</span><div className="tabs"><button className={!json[i]?'active':''} onClick={()=>setJson({...json,[i]:false})}>格式化</button><button className={json[i]?'active':''} onClick={()=>setJson({...json,[i]:true})}>JSON</button></div></div>{json[i]?<pre className="json">{JSON.stringify({question:turn.question,queries:turn.queries,answer:turn.answer,sources:turn.sources},null,2)}</pre>:<div className="markdown"><Markdown text={turn.answer} onCitation={n=>citation(i,n)}/></div>}<div className="answer-footer"><Copy text={json[i]?JSON.stringify(turn,null,2):turn.answer}/></div></div></div></article>)}
 <div ref={bottom}/></section><div className="composer-area">{error&&<div role="alert" className="error">{error}</div>}{loading&&<div role="status" className="loading"><IconLoader2 size={17} className="spin"/>正在检索资料并生成回答…<button className="text-button" onClick={()=>abort.current?.abort()}>取消</button></div>}<form onSubmit={send} className="composer"><textarea aria-label="输入问题" placeholder="输入你的问题，Shift + Enter 换行" maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composer-bottom"><span>{draft.length?`${draft.length} / 4000`:'回答依据知识库资料生成'}</span><button className="primary" type="submit" disabled={loading||!draft.trim()}><IconSend size={17}/>{loading?'生成中':'发送'}</button></div></form><div className="footnote">每次提问独立检索 · 点击答案中的资料编号查看原文</div></div></main>
 <aside className="evidence" aria-label="检索详情"><section className="queries"><h2>拆分的问题 {current&&<span>{current.queries.length}</span>}</h2>{current?<ol>{current.queries.map((q,i)=><li key={i}><span className="number">{i+1}</span><div>{q}</div></li>)}</ol>:<p className="muted">提交问题后，在这里查看检索子问题。</p>}</section><section className="sources"><h2>引用资料{current&&` · ${current.sources.length}`}</h2>{current?.demo&&<p className="demo-note">以下为展示示例，并非本次实时检索结果</p>}{current?.sources.map((s,i)=><details key={`${selected}-${i}`} id={`source-${i+1}`} open tabIndex={-1} className="source"><summary><span className="number">{i+1}</span><div className="source-heading"><strong>{s.reference}</strong><span>{s.file_name}</span><small>PDF 页码：{s.pages?.join('、')||'未记录'} · {s.chunk_id}</small></div><IconChevronDown size={17} className="chevron"/></summary><div className="source-content">{s.content||'该条资料未返回原文。'} </div><div className="source-bottom"><IconFileText size={14}/><span>{s.file_name}</span><Copy text={s.content||s.reference}/></div></details>)}{(!current||!current.sources.length)&&<p className="muted">暂无引用资料</p>}</section></aside></div>
}
